version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: daily
    open-pull-request-limit: 20
  - package-ecosystem: npm
    directory: "/vue"
    schedule:
      interval: daily
    open-pull-request-limit: 20
  - package-ecosystem: npm
    directory: "/webapp"
    schedule:
      interval: daily
    open-pull-request-limit: 20
  - package-ecosystem: pub
    directory: "/mobile"
    schedule:
      interval: daily
    open-pull-request-limit: 20
