# This is a basic workflow that is manually triggered

name: compile dig

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: [push, pull_request, workflow_dispatch]

# This workflow makes x86_64 binaries for mac, windows, and linux.

jobs:
  build:
    runs-on: ubuntu-latest
    name: dig 
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3.3.1
        with: 
          go-version: '^1.19'
        env:
          GOOS: ${{ matrix.targetos }}
          GOARCH: ${{ matrix.arch }}

      - name: Compile dig
        run: |
          make install
          
          
  proof:
    runs-on: ubuntu-latest
    name: prove that v0.46 works
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3.3.1
        with: 
          go-version: '^1.19'

      - name: Prove dig
        run: |
          make install
          digd init test
          rm -rf ~/.dig/data
          cp networks/mainnets/dig-1/genesis.json ~/.dig/config/genesis.json
          URL=https://quicksync.ccvalidators.com/SNAPSHOTS/dig-1_20221029_default.tar.lz4 && wget -O - $URL | lz4 -d | tar -xvf -
          digd start --home ~/.dig
    
